### PR TITLE
Create logos ticker

### PR DESCRIPTION
**Pull request by ChrisJohnRiley**
Testing move to ticker style logos

### CODE REVIEW

**Comment by ChrisJohnRiley** [comment]
Adding links seems to cause layout issues. Removed for now. Can reintroduce these later as required.

**Comment by ChrisJohnRiley** [comment]
Alignment and sizing seem to be fine now. Animation is correctly timed.

Tested and Chrome and Chrome Mobile.

Preview - https://chrisjohnriley-patch-2.mvsp.pages.dev/

**Comment by ChrisJohnRiley** [comment]
After much back and forth, this works effectively now on desktop (Chrome, Safari) and mobile.

- CSS to enable ticker images
- JS to randomise image order
- Added Netflix logo

**Review by acskurucz — APPROVED** [review]
Thank you!

**Pull request merged**
